---
title: "Network with igraph"
author: "gonzalo"
date: "19 de julio de 2018"
output: html_document
---


## Using Igraph to learn R



```{r igraph}

require(igraph)

#Read interaction list
#
web <- read.csv("Data/WeddellSea_FW.csv",header = T,check.names = F)
str(web)

web <- web[,c(2,1)]
str(web)

g <- graph_from_data_frame(web)
g
plot(g)
E(g)#edges of the network
V(g)#vertices of the network
V(g)[name=="Detritus"]#
V(g)[1]
g[1,]
g[,1]
deg <- degree(g,mode="all")#the number of edges or interactions
deg <- degree(g,mode="in")#calculate the in-degree:the number of prey
deg <- degree(g,mode="out")#calculate the out-degree:the number of predators

#plot

plot(g, edge.arrow.size=.4,vertex.label=NA) # Smaller arrow size, not plot names

plot(g, edge.arrow.size=.4,vertex.label=NA,vertex.size=8,layout=layout_with_fr) # Smaller vertex size, specifying a layout .   layout separa los nodos

V(g)$size <- log10(deg)*5+5   # add node degrees to igraph object
V(g)$frame.color <- "white"    # Specify plot options directly on the object 
V(g)$color <- "orange"         #

plot(g, edge.arrow.size=.4,vertex.label=NA,layout=layout_with_lgl)


# Calculate trophic level 

#install.packages("NetIndices")
require(NetIndices)

matadj <- get.adjacency(g,sparse = F)

matadj

tl <- TrophInd(matadj)#trophic level and omnivory
 
tl

tl[tl$TL>=2,] #select rows with trophicc level > 2

#tl[tl$TL<1.5]


# Plot with trophic levels

lMat <-matrix(
  nrow=vcount(g),  # Rows equal to the number of vertices (species)
  ncol=2
)

lMat[,2]<-jitter(tl$TL,0.1)              # y-axis value based on trophic level
lMat[,1]<-runif(vcount(g))   # randomly assign along x-axis

plot(g, edge.width=.3,edge.arrow.size=.4,
       vertex.label=NA,
       edge.color="grey50",
       edge.curved=0.3, layout=lMat)

require(RColorBrewer)

colTL <- as.numeric(cut(tl$TL,11))#divide trophic levels in 11 segments
colnet <-  brewer.pal(11,"RdYlGn")#assign colors to trophic levels
V(g)$color <- colnet[12-colTL]#add colors to the igraph object

plot(g, edge.width=.3,edge.arrow.size=.4,
       vertex.label=NA,
       edge.color="grey50",
       edge.curved=0.3, layout=lMat)

#read a network in adjacent matrix 

web <- read.csv("Data/BarentsBoreal_FW.csv", header = T,check.names = F)

ncol(web)
nrow(web)

if ((ncol(web)-1)==nrow(web))#the adjacency matrix must be square
{
  tmp0 <- ncol(web)
  tmp1 <- web[,2:tmp0]
  tmp2 <- as.matrix(tmp1)
  g <- graph_from_adjacency_matrix(tmp2)
} else 
  {
  warning("El numero de filas no es igual al numero de columnas en la matriz de adyacencia")
  }
g

#calculate other network indices

deg <- degree(g, mode="out") # calculate the in-degree: the number of predators  

V(g)$outdegree <-  deg

nTop <- length(V(g)[outdegree==0]) # Top predators do not have predators

deg <- degree(g, mode="in") # calculate the in-degree: the number of preys

V(g)$indegree <-  deg

nBasal <- length(V(g)[indegree==0]) # Basal species do not have preys 

vcount(g)-nTop-nBasal # Intermediate species

size <- vcount(g)

links <- ecount(g)

linkDen <- links/size          # Linkage density

conn <- links/size^2           # Connectance

pathLength <- average.path.length(g)   # Average path length 

clusCoef <- transitivity(g, type = "global")   # Clustering coefficient


```


```{r functions}

require(igraph)

source("R/functions.r")

g <- readEcoNetwork("Data/BarentsBoreal_FW.csv")
plotEcoNetworkTrophLevel(g)
topologicalIndicesEcoNetwork(g)

```


## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
